# -*- coding: utf-8 -*-
# Deployment settings for RadianEngine.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.1/s3e/makefile_builder/mkb.py', 'c:/Users/TestAccount/Desktop/RadianEngine/RadianEngine.mkb', '--deploy-only']
mkb = 'c:/Users/TestAccount/Desktop/RadianEngine/RadianEngine.mkb'
mkf = ['c:\\marmalade\\6.1\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.1\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.1\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.1\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\testac~1\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\testac~1\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\testac~1\\appdata\\roaming\\marmalade\\packages\\6.1.1\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.1\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.1\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.1\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\testac~1\\appdata\\roaming\\marmalade\\packages\\6.1.1\\tiniconv_1.0.1\\tiniconv.mkf']

class DeployConfig(object):
    os = ['android']
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/TestAccount/Desktop/RadianEngine/data-ram/data-gles1/testGroup/testGroup.group.bin', 'testGroup.group.bin', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    os = ['android']
    embed_icf = -1
    name = 'RadianEngine'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'RadianEngine'
    long_caption = 'RadianEngine'
    version = [0, 0, 1]
    config = ['c:/Users/TestAccount/Desktop/RadianEngine/data/app.icf']
    data_dir = 'c:/Users/TestAccount/Desktop/RadianEngine/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Debug_RadianEngine_VC10_arm/RadianEngine.s3e',
                   'release' : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Release_RadianEngine_VC10_arm/RadianEngine.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Debug_RadianEngine_VC10_gcc_mips/RadianEngine.so',
                   'release' : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Release_RadianEngine_VC10_gcc_mips/RadianEngine.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Debug_RadianEngine_VC10_x86/RadianEngine.s86',
                   'release' : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Release_RadianEngine_VC10_x86/RadianEngine.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Debug_RadianEngine_VC10_gcc_arm/RadianEngine.s3e',
                   'release' : r'c:/Users/TestAccount/Desktop/RadianEngine/build_radianengine_vc10/Release_RadianEngine_VC10_gcc_arm/RadianEngine.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
